### PR TITLE
Enable default properties lists in eregistrations

### PR DESCRIPTION
**Pull request by kamsi**
Its very inconvinient having to rely on properties lists in the end systems. Hence, we should move thelists to eregistrations and only enable their mutation in the end systems. Its about following lists:

- `apps-common/business-process-list-properties.js`
- `apps-common/business-process-list-computed-properties.js`
- `apps-common/user-list-properties.js`
- `apps-common/business-process-dispatcher-list-properties.js`

### CODE REVIEW

**Comment by kamsi** [comment]
@medikoo adjusts in review

**Comment by kamsi** [comment]
@medikoo I will pass adjusts to review after approval

**Comment by medikoo** [comment]
Looks good, we may either merge it now, or merge it after testing it with adapts, let me know

**Comment by kamsi** [comment]
@medikoo let's wait for adapts

**Comment by mtuchowski** [comment]
@medikoo Concerning `businessName` property. By default it is a static property (https://github.com/egovernment/eregistrations/blob/master/model/business-process-new/base.js#L43) but in the end systems the usage vary:

* Salvador - only computed.
* Guatemala - both computed and static, depending on service.
* Tanzania - both computed and static, depending on service.

Which list in eregistrations should contain this property? We talked with Kamil and think it should be in both by default to minimize work and bugs in end-systems - in worst case scenario (Salvador) it will be pointless for static list.

**Comment by medikoo** [comment]
@mtuchowski In eregistrations its value is empty as its value is service specific.
Occasionally (but I think rarely) it happens that we use this field directly in data forms and it such case it remains static. However in most cases it's linked to some other meaningful property as e.g. `companyName`.

I'd say that easiest and least error-prone approach would be to unconditionally index it  as computed record for any service , and always have it in computed-list. It will work also if property handling is purely static.

**Comment by mtuchowski** [comment]
All adapts OK.

**Pull request merged**
