### PR TITLE
Stats: List of certificates improvement

### PR DESCRIPTION
**Pull request by mtuchowski**
Information we want : the list of emitted certificates, for a given period, for a given service or for all the services. 

We can achieve this by modifying the table of "Completed files" page. The mockup of the page with the needed modifications is here : http://3m5fo4.axshare.com/#p=completed_files

Those modifications are:

* Change the name of the Service for it icon with tooltip
* remove the short name column, it is redundant information
* change "Waiting" for "Submitted" (= that has been submitted to part B but is not yet pending for processing)
* Add the columns "Ready for withdrawn", "Withdrawn", "Sent back"
* the first table remains unchanged, it will be filtered by the "Services" (by removing lines) and "Period" (for the Period column). We can remove the %, it does not add a lot of information and make the reading difficult.

### CODE REVIEW

**Comment by mtuchowski** [comment]
Adapts to end systems:

https://github.com/egovernment/eregistrations-salvador/pull/1751
https://github.com/egovernment/eregistrations-guatemala/pull/1055
https://github.com/egovernment/eregistrations-tanzania/issues/1062

**Comment by mtuchowski** [comment]
All adapts tested and ready.

**Comment by roxanadina** [comment]
@mtuchowski 
as I was saying - try elsalvador, an individual trader request
I was having a request with NIT and AMSS registrations.  NIT was processed, file got to front-desk, file was withdrew. AMSS not processed yet.

I the table I ended up with AMSS line- 1 pending (correct) and 1 withdrew (not correct)

**Comment by mtuchowski** [comment]
Ready.

**Pull request merged**
