### PR TITLE
Split currency in toWSJSON

### PR DESCRIPTION
**Pull request by kamsi**
For currency type entries we want: value and currency keys.

### CODE REVIEW

**Comment by kamsi** [comment]
Solves partially this: https://github.com/egovernment/eregistrations-guatemala/pull/1059

**Comment by roxanadina** [comment]
@kamsi, maybe we name the "value"property amount. This is the format in the costs section, better if it is uniform :)

**Comment by kamsi** [comment]
@roxanadina I adjusted the PR. @brajovela  check the changes pls.

@roxanadina examples from ELS:

schema: https://gist.github.com/kamsi/dcac61ee792af688942acf3088401fbf
data: https://gist.github.com/kamsi/78a1bc27c8b66d2d5d643d96d10168d9

**Comment by brajovela** [comment]
Thanks @kamsi, i will check!

**Pull request merged**
