### PR TITLE
Rection reasons refactor

### PR DESCRIPTION
**Pull request by kamsi**
@raunokulla @mtuchowski @ilja903 @roxanadina This will be from now on the main branch for the milestone of rejection-reasons milestone, all work should be merged here. Once this is merged, the new view of rejection reasons must be completely done.
The mock of the new functionality is here: http://3m5fo4.axshare.com/#p=4__table_of_reasons_of_rejections
The Corresponding issues in Jira for the time are:

https://unctad.atlassian.net/browse/EV2CORE-26
https://unctad.atlassian.net/browse/EV2CORE-42
https://unctad.atlassian.net/browse/EV2CORE-43
https://unctad.atlassian.net/browse/EV2CORE-27
https://unctad.atlassian.net/browse/EV2CORE-2
https://unctad.atlassian.net/browse/EV2CORE-3
https://unctad.atlassian.net/browse/EV2CORE-4
https://unctad.atlassian.net/browse/EV2CORE-35
https://unctad.atlassian.net/browse/EV2CORE-40

### CODE REVIEW

**Comment by mtuchowski** [comment]
In GT:

```console
Request error (unhandled)
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.exports.log-client-error.validate (/home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/mano/controller/server.js:242:21)
    at Object.normalizedConf.controller (/home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/post-controller-router/index.js:129:27)
    at null.<anonymous> (/home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/controller-router/index.js:131:38)
    at Object.<anonymous> (/home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/mano/server/post-basic-router.js:28:20)
    at Array.<anonymous> (/home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/mano/lib/server/server/post-apps-controller-handler.js:11:20)
    at self (/home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/mano/lib/server/server/post.js:52:24)
    at /home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/mano/lib/server/server/post.js:53:4
    at call (/home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/connect/lib/proto.js:205:7)
    at next (/home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/connect/lib/proto.js:149:5)
    at multipart (/home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/connect-multiparty/index.js:42:27)
    at /home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/mano/lib/server/server/body-parser.js:27:4
    at /home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/body-parser/lib/read.js:121:5
    at invokeCallback (/home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/body-parser/node_modules/raw-body/index.js:251:16)
    at done (/home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/body-parser/node_modules/raw-body/index.js:240:7)
    at IncomingMessage.onEnd (/home/mtuchowski/Projects/egovernment/eregistrations-guatemala/node_modules/body-parser/node_modules/raw-body/index.js:297:7)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:511:9)
    at process._tickCallback (node.js:425:17)
```

**Comment by mtuchowski** [comment]
Oh, sorry, that was a client error error. Now on the client:

```console
Error: Route cancelled, as next one took action
```

**Comment by mtuchowski** [comment]
This was while clicking the loop on one of the rejected files.

**Comment by mtuchowski** [comment]
hmm, after restarting the app and reloading the page, the loop icon worked.

**Comment by kamsi** [comment]
@mtuchowski I just checked and this error already occurs on production for the older solution... I will prepare separate ticket to fix it.

**Pull request merged**
